//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef AttrListIndexes_h
#define AttrListIndexes_h
class AttrListIndexes;

#include "Rtypes.h"

class AttrListIndexes {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned short m_typeIndex;    //
   unsigned short m_objIndex;     //

   AttrListIndexes();
   AttrListIndexes(AttrListIndexes && ) = default;
   AttrListIndexes &operator=(const AttrListIndexes & );
   AttrListIndexes(const AttrListIndexes & );
   virtual ~AttrListIndexes();

};
#endif
