//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef DataHeader_p6_h
#define DataHeader_p6_h
class DataHeader_p6;

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include "DataHeader_p6.h"
#include <string>

class DataHeader_p6 {

public:
// Nested classes forward declaration.
class FullElement;

public:
// Nested classes declaration.
class FullElement {

public:
// Nested classes declaration.

public:
// Data Members.
   ULong64_t   oid2;        //
   unsigned int dbIdx;       //index to DHForm entry with DB GUID & technology
   unsigned int objIdx;      //index to DHForm entry with object data

   FullElement();
   FullElement(FullElement && ) = default;
   FullElement &operator=(const FullElement & );
   FullElement(const FullElement & );
   virtual ~FullElement();

};

public:
// Data Members.
   unsigned int m_commonDbIndex;    //
   ULong64_t    m_commonOID2;       //
   vector<int>  m_shortElements;    //
   vector<DataHeader_p6::FullElement> m_fullElements;     //
   unsigned int                       m_provenanceSize;    //
   string                             m_dhFormToken;       //

   DataHeader_p6();
   DataHeader_p6(DataHeader_p6 && ) = default;
   DataHeader_p6 &operator=(const DataHeader_p6 & );
   DataHeader_p6(const DataHeader_p6 & );
   virtual ~DataHeader_p6();

};
#endif
