//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef ElementLink_xAOD__CutBookkeeperContainer_v1__h
#define ElementLink_xAOD__CutBookkeeperContainer_v1__h
namespace xAOD {
#ifndef xAOD__CutBookkeeperContainer_v1_h
#define xAOD__CutBookkeeperContainer_v1_h
enum CutBookkeeperContainer_v1 { kDefault_CutBookkeeperContainer_v1 };
#endif
} // end of namespace.
template <typename T0> class ElementLink;
template <> class ElementLink<xAOD::CutBookkeeperContainer_v1>;

#include "Rtypes.h"
namespace xAOD {
#ifndef xAOD__CutBookkeeperContainer_v1_h
#define xAOD__CutBookkeeperContainer_v1_h
enum CutBookkeeperContainer_v1 { kDefault_CutBookkeeperContainer_v1 };
#endif
} // end of namespace.
#include "ElementLinkBase.h"

template <typename T0> class ElementLink;
template <> class ElementLink<xAOD::CutBookkeeperContainer_v1> : public ElementLinkBase {

public:
// Nested classes declaration.

public:
// Data Members.

   ElementLink();
   ElementLink(ElementLink && ) = default;
   ElementLink &operator=(const ElementLink & );
   ElementLink(const ElementLink & );
   virtual ~ElementLink();

};
#endif
