//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef ElementLink_DataVector_xAOD__IParticle____h
#define ElementLink_DataVector_xAOD__IParticle____h
namespace xAOD {
class IParticle;
} // end of namespace.
#ifndef DataVector_xAOD__IParticle__h
#define DataVector_xAOD__IParticle__h
template <typename T0> class DataVector;
template <> class DataVector<xAOD::IParticle> {
public:
operator int() { return 0; };
}; // end of class.
#endif
template <typename T0> class ElementLink;
template <> class ElementLink<DataVector<xAOD::IParticle> >;

#include "Rtypes.h"
namespace xAOD {
class IParticle;
} // end of namespace.
#ifndef DataVector_xAOD__IParticle__h
#define DataVector_xAOD__IParticle__h
template <typename T0> class DataVector;
template <> class DataVector<xAOD::IParticle> {
public:
operator int() { return 0; };
}; // end of class.
#endif
#include "ElementLinkBase.h"

template <typename T0> class ElementLink;
template <> class ElementLink<DataVector<xAOD::IParticle> > : public ElementLinkBase {

public:
// Nested classes declaration.

public:
// Data Members.

   ElementLink();
   ElementLink(ElementLink && ) = default;
   ElementLink &operator=(const ElementLink & );
   ElementLink(const ElementLink & );
   virtual ~ElementLink();

};
#endif
