//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef ElementLink_DataVector_xAOD__NeutralParticle_v1____h
#define ElementLink_DataVector_xAOD__NeutralParticle_v1____h
namespace xAOD {
#ifndef xAOD__NeutralParticle_v1_h
#define xAOD__NeutralParticle_v1_h
enum NeutralParticle_v1 { kDefault_NeutralParticle_v1 };
#endif
} // end of namespace.
#ifndef DataVector_xAOD__NeutralParticle_v1__h
#define DataVector_xAOD__NeutralParticle_v1__h
template <typename T0> class DataVector;
template <> class DataVector<xAOD::NeutralParticle_v1> {
public:
operator int() { return 0; };
}; // end of class.
#endif
template <typename T0> class ElementLink;
template <> class ElementLink<DataVector<xAOD::NeutralParticle_v1> >;

#include "Rtypes.h"
namespace xAOD {
#ifndef xAOD__NeutralParticle_v1_h
#define xAOD__NeutralParticle_v1_h
enum NeutralParticle_v1 { kDefault_NeutralParticle_v1 };
#endif
} // end of namespace.
#ifndef DataVector_xAOD__NeutralParticle_v1__h
#define DataVector_xAOD__NeutralParticle_v1__h
template <typename T0> class DataVector;
template <> class DataVector<xAOD::NeutralParticle_v1> {
public:
operator int() { return 0; };
}; // end of class.
#endif
#include "ElementLinkBase.h"

template <typename T0> class ElementLink;
template <> class ElementLink<DataVector<xAOD::NeutralParticle_v1> > : public ElementLinkBase {

public:
// Nested classes declaration.

public:
// Data Members.

   ElementLink();
   ElementLink(ElementLink && ) = default;
   ElementLink &operator=(const ElementLink & );
   ElementLink(const ElementLink & );
   virtual ~ElementLink();

};
#endif
