//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef ElementLinkBase_h
#define ElementLinkBase_h
class ElementLinkBase;

#include "Rtypes.h"

class ElementLinkBase {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int m_persKey;    //
   unsigned int m_persIndex;    //

   ElementLinkBase();
   ElementLinkBase(ElementLinkBase && ) = default;
   ElementLinkBase &operator=(const ElementLinkBase & );
   ElementLinkBase(const ElementLinkBase & );
   virtual ~ElementLinkBase();

};
#endif
