//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef EventType_p3_h
#define EventType_p3_h
class EventType_p3;

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include <string>

class EventType_p3 {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<bool> m_bit_mask;    //
   string       m_user_type;    //
   vector<float> m_mc_event_weights;    //
   unsigned int  m_mc_channel_number;    //
   unsigned long m_mc_event_number;      //

   EventType_p3();
   EventType_p3(EventType_p3 && ) = default;
   EventType_p3 &operator=(const EventType_p3 & );
   EventType_p3(const EventType_p3 & );
   virtual ~EventType_p3();

};
#endif
