//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef EventStreamInfo_p3_h
#define EventStreamInfo_p3_h
class EventStreamInfo_p3;

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>
#include <utility>
#include "EventType_p3.h"

class EventStreamInfo_p3 {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int m_numberOfEvents;    //Number of Events
   vector<unsigned int> m_runNumbers;        //Run#
   vector<unsigned int> m_lumiBlockNumbers;    //LumiBlock#
   vector<string>       m_processingTags;      //ProcessingTags
   vector<pair<unsigned int,string> > m_itemList;            //ItemList
   vector<EventType_p3>               m_eventTypes;          //EventTypes

   EventStreamInfo_p3();
   EventStreamInfo_p3(EventStreamInfo_p3 && ) = default;
   EventStreamInfo_p3 &operator=(const EventStreamInfo_p3 & );
   EventStreamInfo_p3(const EventStreamInfo_p3 & );
   virtual ~EventStreamInfo_p3();

};
#endif
