//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef Guid_h
#define Guid_h
class Guid;

#include "Rtypes.h"

class Guid {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int m_data1;     //
   unsigned short m_data2;     //
   unsigned short m_data3;     //
   unsigned char  m_data4[8];    //

   Guid();
   Guid(Guid && ) = default;
   Guid &operator=(const Guid & );
   Guid(const Guid & );
   virtual ~Guid();

};
#endif
