//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef ILockable_h
#define ILockable_h
class ILockable;

#include "Rtypes.h"

class ILockable {

public:
// Nested classes declaration.

public:
// Data Members.

   ILockable();
   ILockable(ILockable && ) = default;
   ILockable &operator=(const ILockable & );
   ILockable(const ILockable & );
   virtual ~ILockable();

};
#endif
