//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef IOVMetaDataContainer_p1_h
#define IOVMetaDataContainer_p1_h
class IOVMetaDataContainer_p1;

#include "Rtypes.h"
#include "Riostream.h"
#include <string>
#include "IOVPayloadContainer_p1.h"

class IOVMetaDataContainer_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   string      m_folderName;    //
   string      m_folderDescription;    //
   IOVPayloadContainer_p1 m_payload;              //

   IOVMetaDataContainer_p1();
   IOVMetaDataContainer_p1(IOVMetaDataContainer_p1 && ) = default;
   IOVMetaDataContainer_p1 &operator=(const IOVMetaDataContainer_p1 & );
   IOVMetaDataContainer_p1(const IOVMetaDataContainer_p1 & );
   virtual ~IOVMetaDataContainer_p1();

};
#endif
