#ifdef __CINT__

#pragma link C++ class EventStreamInfo_p3+;
#pragma link C++ class IOVMetaDataContainer_p1+;
#pragma link C++ class xAOD::FileMetaDataAuxInfo_v1+;
#pragma link C++ class xAOD::AuxInfoBase+;
#pragma link C++ class SG::IAuxStore+;
#pragma link C++ class SG::IConstAuxStore+;
#pragma link C++ class SG::IAuxStoreIO+;
#pragma link C++ class SG::IAuxStoreHolder+;
#pragma link C++ class ILockable+;
#pragma link C++ class xAOD::TruthMetaDataAuxContainer_v1+;
#pragma link C++ class xAOD::AuxContainerBase+;
#pragma link C++ class xAOD::CutBookkeeperAuxContainer_v1+;
#pragma link C++ class ElementLink<xAOD::CutBookkeeperContainer_v1>+;
#pragma link C++ class ElementLinkBase+;
#pragma link C++ class xAOD::TriggerMenuAuxContainer_v1+;
#pragma link C++ class xAOD::LumiBlockRangeAuxContainer_v1+;
#pragma link C++ class EventType_p3+;
#pragma link C++ class xAOD::FileMetaData_v1+;
#pragma link C++ class SG::AuxElement+;
#pragma link C++ class SG::IAuxElement+;
#pragma link C++ class xAOD::EventFormat_v1+;
#pragma link C++ class xAOD::TriggerMenu_v1+;
#pragma link C++ class xAOD::LumiBlockRange_v1+;
#pragma link C++ class xAOD::TruthMetaData_v1+;
#pragma link C++ class xAOD::CutBookkeeper_v1+;
#pragma link C++ class IOVPayloadContainer_p1+;
#pragma link C++ class IOVPayloadContainer_p1::CondAttrListCollection_p1+;
#pragma link C++ class IOVPayloadContainer_p1::CondAttrListEntry_p1+;
#pragma link C++ class IOVPayloadContainer_p1::IOVRange_p1+;
#pragma link C++ class AttrListIndexes+;
#pragma link C++ class DataHeader_p6+;
#pragma link C++ class DataHeader_p6::FullElement+;
#pragma link C++ class DataHeaderForm_p6+;
#pragma link C++ class DataHeaderForm_p6::DbRecord+;
#pragma link C++ class Guid+;
#pragma link C++ class DataHeaderForm_p6::ObjRecord+;
#pragma link C++ class xAOD::EventInfo_v1+;
#pragma link C++ class xAOD::TrigConfKeys_v1+;
#pragma link C++ class xAOD::TrigDecisionAuxInfo_v1+;
#pragma link C++ class xAOD::TrigDecision_v1+;
#pragma link C++ class xAOD::MissingETAuxAssociationMap_v2+;
#pragma link C++ class ElementLink<DataVector<xAOD::Jet_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::IParticle> >+;
#pragma link C++ class xAOD::MissingETAssociation_v1+;
#pragma link C++ class xAOD::EventShape_v1+;
#pragma link C++ class xAOD::Electron_v1+;
#pragma link C++ class xAOD::Egamma_v1+;
#pragma link C++ class xAOD::IParticle+;
#pragma link C++ class xAOD::Vertex_v1+;
#pragma link C++ class xAOD::MissingET_v1+;
#pragma link C++ class xAOD::Photon_v1+;
#pragma link C++ class xAOD::TauJet_v3+;
#pragma link C++ class xAOD::Muon_v1+;
#pragma link C++ class xAOD::TruthEvent_v1+;
#pragma link C++ class xAOD::TruthEventBase_v1+;
#pragma link C++ class xAOD::CaloCluster_v1+;
#pragma link C++ class xAOD::TruthParticle_v1+;
#pragma link C++ class xAOD::TruthVertex_v1+;
#pragma link C++ class xAOD::Jet_v1+;
#pragma link C++ class xAOD::BTagging_v1+;
#pragma link C++ class xAOD::TrackParticle_v1+;
#pragma link C++ class xAOD::JetAuxContainer_v1+;
#pragma link C++ class xAOD::TauTrack_v1+;
#pragma link C++ class xAOD::TrigComposite_v1+;
#pragma link C++ class ElementLink<DataVector<xAOD::Vertex_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::TrackParticle_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::Egamma_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::TruthParticle_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::CaloCluster_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::BTagging_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::TauTrack_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::TruthVertex_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::MuonSegment_v1> >+;
#pragma link C++ class ElementLink<DataVector<xAOD::NeutralParticle_v1> >+;
#pragma link C++ class xAOD+;
#pragma link C++ class SG+;
#pragma link C++ class xAOD::CutBookkeeperContainer_v1+;
#pragma link C++ class DataVector<xAOD::Jet_v1>+;
#pragma link C++ class DataVector<xAOD::IParticle>+;
#pragma link C++ class DataVector<xAOD::Vertex_v1>+;
#pragma link C++ class DataVector<xAOD::TrackParticle_v1>+;
#pragma link C++ class DataVector<xAOD::Egamma_v1>+;
#pragma link C++ class DataVector<xAOD::TruthParticle_v1>+;
#pragma link C++ class DataVector<xAOD::CaloCluster_v1>+;
#pragma link C++ class DataVector<xAOD::BTagging_v1>+;
#pragma link C++ class DataVector<xAOD::TauTrack_v1>+;
#pragma link C++ class DataVector<xAOD::TruthVertex_v1>+;
#pragma link C++ class xAOD::MuonSegment_v1+;
#pragma link C++ class DataVector<xAOD::MuonSegment_v1>+;
#pragma link C++ class xAOD::NeutralParticle_v1+;
#pragma link C++ class DataVector<xAOD::NeutralParticle_v1>+;
#endif
