//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef SG__IAuxStoreHolder_h
#define SG__IAuxStoreHolder_h
namespace SG {
class IAuxStoreHolder;
} // end of namespace.

#include "Rtypes.h"

namespace SG {
class IAuxStoreHolder {

public:
// Nested classes declaration.

public:
// Data Members.

   IAuxStoreHolder();
   IAuxStoreHolder(IAuxStoreHolder && ) = default;
   IAuxStoreHolder &operator=(const IAuxStoreHolder & );
   IAuxStoreHolder(const IAuxStoreHolder & );
   virtual ~IAuxStoreHolder();

};
} // namespace
#endif
