//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef SG__AuxElement_h
#define SG__AuxElement_h
namespace SG {
class AuxElement;
} // end of namespace.

#include "Rtypes.h"
#include "SG__IAuxElement.h"

namespace SG {
class AuxElement : public SG::IAuxElement {

public:
// Nested classes declaration.

public:
// Data Members.

   AuxElement();
   AuxElement(AuxElement && ) = default;
   AuxElement &operator=(const AuxElement & );
   AuxElement(const AuxElement & );
   virtual ~AuxElement();

};
} // namespace
#endif
