//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef SG__IConstAuxStore_h
#define SG__IConstAuxStore_h
namespace SG {
class IConstAuxStore;
} // end of namespace.

#include "Rtypes.h"

namespace SG {
class IConstAuxStore {

public:
// Nested classes declaration.

public:
// Data Members.

   IConstAuxStore();
   IConstAuxStore(IConstAuxStore && ) = default;
   IConstAuxStore &operator=(const IConstAuxStore & );
   IConstAuxStore(const IConstAuxStore & );
   virtual ~IConstAuxStore();

};
} // namespace
#endif
