//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef SG__IAuxStore_h
#define SG__IAuxStore_h
namespace SG {
class IAuxStore;
} // end of namespace.

#include "Rtypes.h"
#include "SG__IConstAuxStore.h"

namespace SG {
class IAuxStore : public SG::IConstAuxStore {

public:
// Nested classes declaration.

public:
// Data Members.

   IAuxStore();
   IAuxStore(IAuxStore && ) = default;
   IAuxStore &operator=(const IAuxStore & );
   IAuxStore(const IAuxStore & );
   virtual ~IAuxStore();

};
} // namespace
#endif
