//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef SG__IAuxElement_h
#define SG__IAuxElement_h
namespace SG {
class IAuxElement;
} // end of namespace.

#include "Rtypes.h"

namespace SG {
class IAuxElement {

public:
// Nested classes declaration.

public:
// Data Members.

   IAuxElement();
   IAuxElement(IAuxElement && ) = default;
   IAuxElement &operator=(const IAuxElement & );
   IAuxElement(const IAuxElement & );
   virtual ~IAuxElement();

};
} // namespace
#endif
