//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef SG__IAuxStoreIO_h
#define SG__IAuxStoreIO_h
namespace SG {
class IAuxStoreIO;
} // end of namespace.

#include "Rtypes.h"

namespace SG {
class IAuxStoreIO {

public:
// Nested classes declaration.

public:
// Data Members.

   IAuxStoreIO();
   IAuxStoreIO(IAuxStoreIO && ) = default;
   IAuxStoreIO &operator=(const IAuxStoreIO & );
   IAuxStoreIO(const IAuxStoreIO & );
   virtual ~IAuxStoreIO();

};
} // namespace
#endif
