//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__Electron_v1_h
#define xAOD__Electron_v1_h
namespace xAOD {
class Electron_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__Egamma_v1.h"

namespace xAOD {
class Electron_v1 : public xAOD::Egamma_v1 {

public:
// Nested classes declaration.

public:
// Data Members.

   Electron_v1();
   Electron_v1(Electron_v1 && ) = default;
   Electron_v1 &operator=(const Electron_v1 & );
   Electron_v1(const Electron_v1 & );
   virtual ~Electron_v1();

};
} // namespace
#endif
