//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TruthMetaDataAuxContainer_v1_h
#define xAOD__TruthMetaDataAuxContainer_v1_h
namespace xAOD {
class TruthMetaDataAuxContainer_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__AuxContainerBase.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;

namespace xAOD {
class TruthMetaDataAuxContainer_v1 : public xAOD::AuxContainerBase {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<vector<string> > weightNames;    //
   vector<unsigned int>    mcChannelNumber;    //
   vector<string>          lhefGenerator;      //Generator for LHE file events
   vector<string>          generators;         //Generators for this dataset
   vector<string>          evgenProcess;       //Physics process in this dataset
   vector<string>          evgenTune;          //Hadronization and UE tune used for this dataset
   vector<string>          hardPDF;            //PDF used for the hard process
   vector<string>          softPDF;            //PDF used for the tune / shower / hadronization

   TruthMetaDataAuxContainer_v1();
   TruthMetaDataAuxContainer_v1(TruthMetaDataAuxContainer_v1 && ) = default;
   TruthMetaDataAuxContainer_v1 &operator=(const TruthMetaDataAuxContainer_v1 & );
   TruthMetaDataAuxContainer_v1(const TruthMetaDataAuxContainer_v1 & );
   virtual ~TruthMetaDataAuxContainer_v1();

};
} // namespace
#endif
