//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TrigDecision_v1_h
#define xAOD__TrigDecision_v1_h
namespace xAOD {
class TrigDecision_v1;
} // end of namespace.

#include "Rtypes.h"
#include "SG__AuxElement.h"

namespace xAOD {
class TrigDecision_v1 : public SG::AuxElement {

public:
// Nested classes declaration.

public:
// Data Members.

   TrigDecision_v1();
   TrigDecision_v1(TrigDecision_v1 && ) = default;
   TrigDecision_v1 &operator=(const TrigDecision_v1 & );
   TrigDecision_v1(const TrigDecision_v1 & );
   virtual ~TrigDecision_v1();

};
} // namespace
#endif
