//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__JetAuxContainer_v1_h
#define xAOD__JetAuxContainer_v1_h
namespace xAOD {
class JetAuxContainer_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__AuxContainerBase.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;
#include "ElementLink_DataVector_xAOD__IParticle___.h"
namespace std {} using namespace std;

namespace xAOD {
class JetAuxContainer_v1 : public xAOD::AuxContainerBase {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<float> pt;          //
   vector<float> eta;         //
   vector<float> phi;         //
   vector<float> m;           //
   vector<vector<ElementLink<DataVector<xAOD::IParticle> > > > constituentLinks;    //
   vector<vector<float> >                                      constituentWeights;    //

   JetAuxContainer_v1();
   JetAuxContainer_v1(JetAuxContainer_v1 && ) = default;
   JetAuxContainer_v1 &operator=(const JetAuxContainer_v1 & );
   JetAuxContainer_v1(const JetAuxContainer_v1 & );
   virtual ~JetAuxContainer_v1();

};
} // namespace
#endif
