//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__MuonSegment_v1_h
#define xAOD__MuonSegment_v1_h
namespace xAOD {
class MuonSegment_v1;
} // end of namespace.

#include "Rtypes.h"

#endif
