//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__IParticle_h
#define xAOD__IParticle_h
namespace xAOD {
class IParticle;
} // end of namespace.

#include "Rtypes.h"
#include "SG__AuxElement.h"

namespace xAOD {
class IParticle : public SG::AuxElement {

public:
// Nested classes declaration.

public:
// Data Members.

   IParticle();
   IParticle(IParticle && ) = default;
   IParticle &operator=(const IParticle & );
   IParticle(const IParticle & );
   virtual ~IParticle();

};
} // namespace
#endif
