//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TrackParticle_v1_h
#define xAOD__TrackParticle_v1_h
namespace xAOD {
class TrackParticle_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__IParticle.h"

namespace xAOD {
class TrackParticle_v1 : public xAOD::IParticle {

public:
// Nested classes declaration.

public:
// Data Members.

   TrackParticle_v1();
   TrackParticle_v1(TrackParticle_v1 && ) = default;
   TrackParticle_v1 &operator=(const TrackParticle_v1 & );
   TrackParticle_v1(const TrackParticle_v1 & );
   virtual ~TrackParticle_v1();

};
} // namespace
#endif
