//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TruthMetaData_v1_h
#define xAOD__TruthMetaData_v1_h
namespace xAOD {
class TruthMetaData_v1;
} // end of namespace.

#include "Rtypes.h"
#include "SG__AuxElement.h"

namespace xAOD {
class TruthMetaData_v1 : public SG::AuxElement {

public:
// Nested classes declaration.

public:
// Data Members.

   TruthMetaData_v1();
   TruthMetaData_v1(TruthMetaData_v1 && ) = default;
   TruthMetaData_v1 &operator=(const TruthMetaData_v1 & );
   TruthMetaData_v1(const TruthMetaData_v1 & );
   virtual ~TruthMetaData_v1();

};
} // namespace
#endif
