//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__CaloCluster_v1_h
#define xAOD__CaloCluster_v1_h
namespace xAOD {
class CaloCluster_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__IParticle.h"

namespace xAOD {
class CaloCluster_v1 : public xAOD::IParticle {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int m_samplingPattern;    //

   CaloCluster_v1();
   CaloCluster_v1(CaloCluster_v1 && ) = default;
   CaloCluster_v1 &operator=(const CaloCluster_v1 & );
   CaloCluster_v1(const CaloCluster_v1 & );
   virtual ~CaloCluster_v1();

};
} // namespace
#endif
