//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__FileMetaDataAuxInfo_v1_h
#define xAOD__FileMetaDataAuxInfo_v1_h
namespace xAOD {
class FileMetaDataAuxInfo_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__AuxInfoBase.h"
#include "Riostream.h"
#include <string>
#include <vector>

namespace xAOD {
class FileMetaDataAuxInfo_v1 : public xAOD::AuxInfoBase {

public:
// Nested classes declaration.

public:
// Data Members.
   string      productionRelease;    //
   string      dataType;             //
   vector<unsigned int> runNumbers;           //
   vector<unsigned int> lumiBlocks;           //

   FileMetaDataAuxInfo_v1();
   FileMetaDataAuxInfo_v1(FileMetaDataAuxInfo_v1 && ) = default;
   FileMetaDataAuxInfo_v1 &operator=(const FileMetaDataAuxInfo_v1 & );
   FileMetaDataAuxInfo_v1(const FileMetaDataAuxInfo_v1 & );
   virtual ~FileMetaDataAuxInfo_v1();

};
} // namespace
#endif
