//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__EventFormat_v1_h
#define xAOD__EventFormat_v1_h
namespace xAOD {
class EventFormat_v1;
} // end of namespace.

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

namespace xAOD {
class EventFormat_v1 {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<string> m_branchNames;    //
   vector<string> m_classNames;     //
   vector<string> m_parentNames;    //
   vector<unsigned int> m_branchHashes;    //

   EventFormat_v1();
   EventFormat_v1(EventFormat_v1 && ) = default;
   EventFormat_v1 &operator=(const EventFormat_v1 & );
   EventFormat_v1(const EventFormat_v1 & );
   virtual ~EventFormat_v1();

};
} // namespace
#endif
