//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TriggerMenuAuxContainer_v1_h
#define xAOD__TriggerMenuAuxContainer_v1_h
namespace xAOD {
class TriggerMenuAuxContainer_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__AuxContainerBase.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace xAOD {
class TriggerMenuAuxContainer_v1 : public xAOD::AuxContainerBase {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<unsigned int> smk;         //
   vector<unsigned int> l1psk;       //
   vector<unsigned int> hltpsk;      //
   vector<vector<unsigned short> > itemCtpIds;    //
   vector<vector<string> >         itemNames;     //
   vector<vector<float> >          itemPrescales;    //
   vector<vector<unsigned short> > chainIds;         //
   vector<vector<string> >         chainNames;       //
   vector<vector<string> >         chainParentNames;    //
   vector<vector<float> >          chainPrescales;      //
   vector<vector<float> >          chainRerunPrescales;    //
   vector<vector<float> >          chainPassthroughPrescales;    //
   vector<vector<vector<unsigned int> > > chainSignatureCounters;       //
   vector<vector<vector<int> > >          chainSignatureLogics;         //
   vector<vector<vector<vector<string> > > > chainSignatureOutputTEs;      //
   vector<vector<vector<string> > >          chainSignatureLabels;         //
   vector<vector<vector<string> > >          sequenceInputTEs;             //
   vector<vector<string> >                   sequenceOutputTEs;            //
   vector<vector<vector<string> > >          sequenceAlgorithms;           //
   vector<vector<vector<unsigned short> > >  bunchGroupBunches;            //

   TriggerMenuAuxContainer_v1();
   TriggerMenuAuxContainer_v1(TriggerMenuAuxContainer_v1 && ) = default;
   TriggerMenuAuxContainer_v1 &operator=(const TriggerMenuAuxContainer_v1 & );
   TriggerMenuAuxContainer_v1(const TriggerMenuAuxContainer_v1 & );
   virtual ~TriggerMenuAuxContainer_v1();

};
} // namespace
#endif
