//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TrigConfKeys_v1_h
#define xAOD__TrigConfKeys_v1_h
namespace xAOD {
class TrigConfKeys_v1;
} // end of namespace.

#include "Rtypes.h"

namespace xAOD {
class TrigConfKeys_v1 {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int m_smk;       //
   unsigned int m_l1psk;     //
   unsigned int m_hltpsk;    //

   TrigConfKeys_v1();
   TrigConfKeys_v1(TrigConfKeys_v1 && ) = default;
   TrigConfKeys_v1 &operator=(const TrigConfKeys_v1 & );
   TrigConfKeys_v1(const TrigConfKeys_v1 & );
   virtual ~TrigConfKeys_v1();

};
} // namespace
#endif
