//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__MissingETAuxAssociationMap_v2_h
#define xAOD__MissingETAuxAssociationMap_v2_h
namespace xAOD {
class MissingETAuxAssociationMap_v2;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__AuxContainerBase.h"
#include "Riostream.h"
#include <vector>
#include "ElementLink_DataVector_xAOD__Jet_v1___.h"
namespace std {} using namespace std;
#include "ElementLink_DataVector_xAOD__IParticle___.h"
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace xAOD {
class MissingETAuxAssociationMap_v2 : public xAOD::AuxContainerBase {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<ElementLink<DataVector<xAOD::Jet_v1> > > jetLink;     //@brief Link to MissingET_v2 object
   vector<vector<ElementLink<DataVector<xAOD::IParticle> > > > objectLinks;    //@brief Link to object contributing to the MissingET_v2 object
   vector<vector<float> >                                      calpx;          //@brief Object constituent calo 4-vector @f$ P_{x} @f$ for overlap removal
   vector<vector<float> >                                      calpy;          //@brief Object constituent calo 4-vector @f$ P_{y} @f$ for overlap removal
   vector<vector<float> >                                      calpz;          //@brief Object constituent calo 4-vector @f$ P_{z} @f$ for overlap removal
   vector<vector<float> >                                      cale;           //@brief Object constituent calo 4-vector @f$ E @f$ for overlap removal
   vector<vector<float> >                                      calsumpt;       //@brief Object constituent calo 4-vector sumpt for overlap removal
   vector<vector<unsigned long> >                              calkey;         //@brief Object constituent calo region key for overlap removal
   vector<vector<float> >                                      trkpx;          //@brief Object constituent track 4-vector @f$ P_{x} @f$ for overlap removal
   vector<vector<float> >                                      trkpy;          //@brief Object constituent track 4-vector @f$ P_{y} @f$ for overlap removal
   vector<vector<float> >                                      trkpz;          //@brief Object constituent track 4-vector @f$ P_{z} @f$ for overlap removal
   vector<vector<float> >                                      trke;           //@brief Object constituent track 4-vector @f$ E @f$ for overlap removal
   vector<vector<float> >                                      trksumpt;       //@brief Object constituent track 4-vector sumpt for overlap removal
   vector<vector<unsigned long> >                              trkkey;         //@brief Object constituent track region key for overlap removal
   vector<float>                                               jettrkpx;       //@brief Jet track 4-vector @f$ P_{x} @f$ for overlap removal
   vector<float>                                               jettrkpy;       //@brief Jet track 4-vector @f$ P_{y} @f$ for overlap removal
   vector<float>                                               jettrkpz;       //@brief Jet track 4-vector @f$ P_{z} @f$ for overlap removal
   vector<float>                                               jettrke;        //@brief Jet track 4-vector @f$ E @f$ for overlap removal
   vector<float>                                               jettrksumpt;    //@brief Jet track 4-vector sumpt for overlap removal
   vector<vector<vector<unsigned long> > >                     overlapIndices;    //@brief Indices of objects that overlap one another in an association
   vector<vector<vector<unsigned char> > >                     overlapTypes;      //@brief Types of overlap between matched objects
   vector<char>                                                isMisc;            //@brief Flags an association as the miscellaneous association

   MissingETAuxAssociationMap_v2();
   MissingETAuxAssociationMap_v2(MissingETAuxAssociationMap_v2 && ) = default;
   MissingETAuxAssociationMap_v2 &operator=(const MissingETAuxAssociationMap_v2 & );
   MissingETAuxAssociationMap_v2(const MissingETAuxAssociationMap_v2 & );
   virtual ~MissingETAuxAssociationMap_v2();

};
} // namespace
#endif
