//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__AuxInfoBase_h
#define xAOD__AuxInfoBase_h
namespace xAOD {
class AuxInfoBase;
} // end of namespace.

#include "Rtypes.h"
#include "SG__IAuxStore.h"
#include "SG__IAuxStoreIO.h"
#include "SG__IAuxStoreHolder.h"
#include "ILockable.h"

namespace xAOD {
class AuxInfoBase : public SG::IAuxStore , public SG::IAuxStoreIO , public SG::IAuxStoreHolder , public ILockable {

public:
// Nested classes declaration.

public:
// Data Members.

   AuxInfoBase();
   AuxInfoBase(AuxInfoBase && ) = default;
   AuxInfoBase &operator=(const AuxInfoBase & );
   AuxInfoBase(const AuxInfoBase & );
   virtual ~AuxInfoBase();

};
} // namespace
#endif
