//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TruthParticle_v1_h
#define xAOD__TruthParticle_v1_h
namespace xAOD {
class TruthParticle_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__IParticle.h"

namespace xAOD {
class TruthParticle_v1 : public xAOD::IParticle {

public:
// Nested classes declaration.

public:
// Data Members.

   TruthParticle_v1();
   TruthParticle_v1(TruthParticle_v1 && ) = default;
   TruthParticle_v1 &operator=(const TruthParticle_v1 & );
   TruthParticle_v1(const TruthParticle_v1 & );
   virtual ~TruthParticle_v1();

};
} // namespace
#endif
