//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TruthEvent_v1_h
#define xAOD__TruthEvent_v1_h
namespace xAOD {
class TruthEvent_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__TruthEventBase_v1.h"

namespace xAOD {
class TruthEvent_v1 : public xAOD::TruthEventBase_v1 {

public:
// Nested classes declaration.

public:
// Data Members.

   TruthEvent_v1();
   TruthEvent_v1(TruthEvent_v1 && ) = default;
   TruthEvent_v1 &operator=(const TruthEvent_v1 & );
   TruthEvent_v1(const TruthEvent_v1 & );
   virtual ~TruthEvent_v1();

};
} // namespace
#endif
