//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__Egamma_v1_h
#define xAOD__Egamma_v1_h
namespace xAOD {
class Egamma_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__IParticle.h"

namespace xAOD {
class Egamma_v1 : public xAOD::IParticle {

public:
// Nested classes declaration.

public:
// Data Members.

   Egamma_v1();
   Egamma_v1(Egamma_v1 && ) = default;
   Egamma_v1 &operator=(const Egamma_v1 & );
   Egamma_v1(const Egamma_v1 & );
   virtual ~Egamma_v1();

};
} // namespace
#endif
