//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__LumiBlockRangeAuxContainer_v1_h
#define xAOD__LumiBlockRangeAuxContainer_v1_h
namespace xAOD {
class LumiBlockRangeAuxContainer_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__AuxContainerBase.h"
#include "Riostream.h"
#include <vector>

namespace xAOD {
class LumiBlockRangeAuxContainer_v1 : public xAOD::AuxContainerBase {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<unsigned int> startRunNumber;    //
   vector<unsigned int> startLumiBlockNumber;    //
   vector<unsigned int> stopRunNumber;           //
   vector<unsigned int> stopLumiBlockNumber;     //
   vector<unsigned int> eventsExpected;          //
   vector<unsigned int> eventsSeen;              //

   LumiBlockRangeAuxContainer_v1();
   LumiBlockRangeAuxContainer_v1(LumiBlockRangeAuxContainer_v1 && ) = default;
   LumiBlockRangeAuxContainer_v1 &operator=(const LumiBlockRangeAuxContainer_v1 & );
   LumiBlockRangeAuxContainer_v1(const LumiBlockRangeAuxContainer_v1 & );
   virtual ~LumiBlockRangeAuxContainer_v1();

};
} // namespace
#endif
