//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TrigDecisionAuxInfo_v1_h
#define xAOD__TrigDecisionAuxInfo_v1_h
namespace xAOD {
class TrigDecisionAuxInfo_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__AuxInfoBase.h"
#include "Riostream.h"
#include <vector>

namespace xAOD {
class TrigDecisionAuxInfo_v1 : public xAOD::AuxInfoBase {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int smk;         //
   char         bgCode;      //
   vector<unsigned int> tav;         //
   vector<unsigned int> tap;         //
   vector<unsigned int> tbp;         //
   unsigned int         lvl2ErrorBits;    //
   unsigned int         efErrorBits;      //
   bool                 lvl2Truncated;    //
   bool                 efTruncated;      //
   vector<unsigned int> lvl2PassedPhysics;    //
   vector<unsigned int> efPassedPhysics;      //
   vector<unsigned int> lvl2PassedRaw;        //
   vector<unsigned int> efPassedRaw;          //
   vector<unsigned int> lvl2PassedThrough;    //
   vector<unsigned int> efPassedThrough;      //
   vector<unsigned int> lvl2Prescaled;        //
   vector<unsigned int> efPrescaled;          //
   vector<unsigned int> lvl2Resurrected;      //
   vector<unsigned int> efResurrected;        //

   TrigDecisionAuxInfo_v1();
   TrigDecisionAuxInfo_v1(TrigDecisionAuxInfo_v1 && ) = default;
   TrigDecisionAuxInfo_v1 &operator=(const TrigDecisionAuxInfo_v1 & );
   TrigDecisionAuxInfo_v1(const TrigDecisionAuxInfo_v1 & );
   virtual ~TrigDecisionAuxInfo_v1();

};
} // namespace
#endif
