//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__CutBookkeeperAuxContainer_v1_h
#define xAOD__CutBookkeeperAuxContainer_v1_h
namespace xAOD {
class CutBookkeeperAuxContainer_v1;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__AuxContainerBase.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;
#include "ElementLink_xAOD__CutBookkeeperContainer_v1_.h"
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace xAOD {
class CutBookkeeperAuxContainer_v1 : public xAOD::AuxContainerBase {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<unsigned int> nameIdentifier;    //
   vector<unsigned int> uniqueIdentifier;    //
   vector<string>       name;                //
   vector<string>       description;         //
   vector<unsigned int> cutLogic;            //
   vector<int>          isTopFilter;         //
   vector<int>          cycle;               //
   vector<string>       inputStream;         //
   vector<vector<string> > outputStreams;       //
   vector<ElementLink<xAOD::CutBookkeeperContainer_v1> > parentLink;          //
   vector<vector<ElementLink<xAOD::CutBookkeeperContainer_v1> > > childrenLinks;       //
   vector<vector<ElementLink<xAOD::CutBookkeeperContainer_v1> > > othersLinks;         //
   vector<vector<ElementLink<xAOD::CutBookkeeperContainer_v1> > > siblingsLinks;       //
   vector<unsigned long>                                          nAcceptedEvents;     //
   vector<double>                                                 sumOfEventWeights;    //
   vector<double>                                                 sumOfEventWeightsSquared;    //

   CutBookkeeperAuxContainer_v1();
   CutBookkeeperAuxContainer_v1(CutBookkeeperAuxContainer_v1 && ) = default;
   CutBookkeeperAuxContainer_v1 &operator=(const CutBookkeeperAuxContainer_v1 & );
   CutBookkeeperAuxContainer_v1(const CutBookkeeperAuxContainer_v1 & );
   virtual ~CutBookkeeperAuxContainer_v1();

};
} // namespace
#endif
