//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 14:25:42 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file PHYSLITE.rntuple
//////////////////////////////////////////////////////////


#ifndef xAOD__TauJet_v3_h
#define xAOD__TauJet_v3_h
namespace xAOD {
class TauJet_v3;
} // end of namespace.

#include "Rtypes.h"
#include "xAOD__IParticle.h"

namespace xAOD {
class TauJet_v3 : public xAOD::IParticle {

public:
// Nested classes declaration.

public:
// Data Members.

   TauJet_v3();
   TauJet_v3(TauJet_v3 && ) = default;
   TauJet_v3 &operator=(const TauJet_v3 & );
   TauJet_v3(const TauJet_v3 & );
   virtual ~TauJet_v3();

};
} // namespace
#endif
