//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 15:04:55 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file FairRoot.rntuple
//////////////////////////////////////////////////////////


#ifndef FairTutPropPoint_h
#define FairTutPropPoint_h
class FairTutPropPoint;

#include "Rtypes.h"
#include "FairMCPoint.h"

class FairTutPropPoint : public FairMCPoint {

public:
// Nested classes declaration.

public:
// Data Members.

   FairTutPropPoint();
   FairTutPropPoint(FairTutPropPoint && ) = default;
   FairTutPropPoint &operator=(const FairTutPropPoint & );
   FairTutPropPoint(const FairTutPropPoint & );
   virtual ~FairTutPropPoint();

   ClassDef(FairTutPropPoint,2); // Generated by MakeProject.
};
#endif
