//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 15:04:55 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file FairRoot.rntuple
//////////////////////////////////////////////////////////


#ifndef FairMCPoint_h
#define FairMCPoint_h
class FairMCPoint;

#include "Rtypes.h"
#include "FairMultiLinkedData_Interface.h"

class FairMCPoint : public FairMultiLinkedData_Interface {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fTrackID;    //Track index
   unsigned int fEventId;    //MC Event id
   Double32_t   fPx;         //Momentum components [GeV]
   Double32_t   fPy;         //Momentum components [GeV]
   Double32_t   fPz;         //Momentum components [GeV]
   Double32_t   fTime;       //Time since event start [ns]
   Double32_t   fLength;     //Track length since creation [cm]
   Double32_t   fELoss;      //Energy loss at this point [GeV]
   int          fDetectorID;    //Detector unique identifier
   Double32_t   fX;             //Position of hit [cm]
   Double32_t   fY;             //Position of hit [cm]
   Double32_t   fZ;             //Position of hit [cm]

   FairMCPoint();
   FairMCPoint(FairMCPoint && ) = default;
   FairMCPoint &operator=(const FairMCPoint & );
   FairMCPoint(const FairMCPoint & );
   virtual ~FairMCPoint();

   ClassDef(FairMCPoint,6); // Generated by MakeProject.
};
#endif
