//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 15:04:55 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file FairRoot.rntuple
//////////////////////////////////////////////////////////


#ifndef FairMCEventHeader_h
#define FairMCEventHeader_h
class FairMCEventHeader;

#include "Rtypes.h"
#include "TObject.h"

class FairMCEventHeader : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fRunId;      ///  Run identifier
   unsigned int fEventId;    ///  Event identifier
   Double32_t   fX;          ///  Primary vertex x [cm]
   Double32_t   fY;          ///  Primary vertex y [cm]
   Double32_t   fZ;          ///  Primary vertex z [cm]
   Double32_t   fT;          ///  Event time [s]
   Double32_t   fB;          ///  Impact parameter [fm] (if relevant)
   int          fNPrim;      ///  Number of input tracks
   bool         fIsSet;      ///  Flag whether variables are filled
   Double32_t   fRotX;       ///  Rotation around x-axis (beam tilt) [rad]
   Double32_t   fRotY;       ///  Rotation around y-axis (beam tilt) [rad]
   Double32_t   fRotZ;       ///  Rotation around z-axis (event plane) [rad]

   FairMCEventHeader();
   FairMCEventHeader(FairMCEventHeader && ) = default;
   FairMCEventHeader &operator=(const FairMCEventHeader & );
   FairMCEventHeader(const FairMCEventHeader & );
   virtual ~FairMCEventHeader();

   ClassDef(FairMCEventHeader,4); // Generated by MakeProject.
};
#endif
