//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 15:04:55 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file FairRoot.rntuple
//////////////////////////////////////////////////////////


#ifndef FairMCTrack_h
#define FairMCTrack_h
class FairMCTrack;

#include "Rtypes.h"
#include "TObject.h"

class FairMCTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         fPdgCode;    //
   int         fMotherId;    //
   Double32_t  fPx;          //
   Double32_t  fPy;          //
   Double32_t  fPz;          //
   Double32_t  fStartX;      //
   Double32_t  fStartY;      //
   Double32_t  fStartZ;      //
   Double32_t  fStartT;      //
   int         fNPoints;     //

   FairMCTrack();
   FairMCTrack(FairMCTrack && ) = default;
   FairMCTrack &operator=(const FairMCTrack & );
   FairMCTrack(const FairMCTrack & );
   virtual ~FairMCTrack();

   ClassDef(FairMCTrack,3); // Generated by MakeProject.
};
#endif
