//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 15:04:55 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file FairRoot.rntuple
//////////////////////////////////////////////////////////


#ifndef FairFileHeader_h
#define FairFileHeader_h
class FairFileHeader;

#include "Rtypes.h"
#include "TNamed.h"
#include "TList.h"

class FairFileHeader : public TNamed {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fRunId;      //
   TList*       fTaskList;    //
   TList*       fFileList;    //

   FairFileHeader();
   FairFileHeader(FairFileHeader && ) = default;
   FairFileHeader &operator=(const FairFileHeader & );
   FairFileHeader(const FairFileHeader & );
   virtual ~FairFileHeader();

   ClassDef(FairFileHeader,3); // Generated by MakeProject.
};
#endif
