//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 15:04:55 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file FairRoot.rntuple
//////////////////////////////////////////////////////////


#ifndef FairMultiLinkedData_h
#define FairMultiLinkedData_h
class FairMultiLinkedData;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <set>
#include "FairLink.h"

class FairMultiLinkedData : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector<FairLink> fLinks;      //
   FairLink              fEntryNr;    //
   int                   fDefaultType;    //

   FairMultiLinkedData();
   FairMultiLinkedData(FairMultiLinkedData && ) = default;
   FairMultiLinkedData &operator=(const FairMultiLinkedData & );
   FairMultiLinkedData(const FairMultiLinkedData & );
   virtual ~FairMultiLinkedData();

   ClassDef(FairMultiLinkedData,5); // Generated by MakeProject.
};
#endif
