//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 23 15:04:55 2025 by ROOT version 6.36.02)
//      from the StreamerInfo in file FairRoot.rntuple
//////////////////////////////////////////////////////////


#ifndef FairLink_h
#define FairLink_h
class FairLink;

#include "Rtypes.h"

class FairLink {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned char fFile;       //
   unsigned short fType;       //
   int            fEntry;      //
   int            fIndex;      //
   float          fWeight;     //

   FairLink();
   FairLink(FairLink && ) = default;
   FairLink &operator=(const FairLink & );
   FairLink(const FairLink & );
   virtual ~FairLink();

   ClassDef(FairLink,6); // Generated by MakeProject.
};
#endif
